### ISSUE TITLE
Error right after enabling addon

### ISSUE THREAD

**Issue by ShawkMusic** [scorpion81/Blender-Molecular-Script#12]
I installed the addon and when trying to enable it, I immediately got this error:

![image](https://user-images.githubusercontent.com/48574225/152773378-330beb44-7ce1-4a7d-bf5d-09979851ac9a.png)

I'm on Blender 3.0.1

**Comment by luckychris** [comment]
did you rename it to core.so?

i am on Mac with Apple M1 Chip...so this doesn't work for me :(

**Comment by wtquin** [comment]
+1 on Fedora Linux 35 running Blender as Flatpak (systemwide). Imported in blender (2nd method following your readme), but cannot enable it due to this error. 
![image](https://user-images.githubusercontent.com/55107945/167012858-7874a2c9-c2f1-41c8-8975-95c25cdb0ce5.png)

**Comment by sykomor** [comment]
same on m1 max blender 3.1
only version I've found was on 2.9 but it doesnt support GPU rendering.
+up for some info if someone find the right version or  some solution!

**Comment by scorpion81** [comment]
Please try out the latest release "1.1.3" . This also contains a "fat" binary for mac os, but I could not test it on a real mac yet.
