### ISSUE TITLE
Type Error on line 226 in operators.py

### ISSUE THREAD

**Issue by sinha5432** [scorpion81/Blender-Molecular-Script#15]
Pops up when I try to start the molecular simulation. 

Working on blender version 3.1.2 on windows with the latest release (1.1.3)

![Screenshot 2022-08-09 185443](https://user-images.githubusercontent.com/46960182/183658117-ee7febd9-047e-4b03-af45-a336e1b7c7c1.png)

**Comment by scorpion81** [comment]
Fixed in release v1.1.4, as well with a crash of blender when Baking UVs is being enabled.
Also added some info in the readme on how to use the UVs actually.
