### ISSUE TITLE
blender3.0 is

### ISSUE THREAD

**Issue by shadowcreeper-hash** [scorpion81/Blender-Molecular-Script#8]

**Comment by shadowcreeper-hash** [comment]
<img width="908" alt="屏幕截图 2021-12-06 050643" src="https://user-images.githubusercontent.com/65867725/144763955-d1f40edd-d917-4980-b33b-94413c6369e9.png">

**Comment by luckychris** [comment]
i have the same error. can i somehow compile my own molecular version?

**Comment by BlueEnd07** [comment]
this is happening because this is made for 2.9 and you are trying to run it in 3.0 or higher it will be fix in next release

**Comment by enzyme69** [comment]
And also this addon does not work on Blender Mac ARM:
```
Traceback (most recent call last):
  File "/Applications/BLENDER_293_LTS/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 386, in enable
    mod.register()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.93/scripts/addons/molecular/__init__.py", line 42, in register
    from . import properties, ui, operators
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.93/scripts/addons/molecular/operators.py", line 7, in <module>
    from . import simulate, core
ImportError: dlopen(/Users/jimmygunawan/Library/Application Support/Blender/2.93/scripts/addons/molecular/core.cpython-39-darwin.so, 0x0002): tried: '/Users/jimmygunawan/Library/Application Support/Blender/2.93/scripts/addons/molecular/core.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))


```

**Comment by scorpion81** [comment]
Please try out the latest release "1.1.3" . This also contains a "fat" binary for mac os, but I could not test it on a real mac yet.
Just saw the architecture name "arm64e" in the error message above... Hmm... i built the mac binary with "arm64". Not sure whether that works... Please test on M1 macs and report back. Or manually compile it... for details how to do this see the release notes.
